version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: damp*1
      MYSQL_DATABASE: damp
      MYSQL_USER: damp
      MYSQL_PASSWORD: damp1234
    volumes:
      - mariadb_data:/var/lib/mysql

  php_apache:
    build:
      context: .
      dockerfile: ./Dockerfile.php
    restart: always
    volumes:
      - ./www/html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb
      
volumes:
  mariadb_data:
